name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🏗 Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🏗 Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🛠 Configure EAS project
        run: npx eas project:init --id a6d21292-4c36-49a6-b5d6-da4772a144ca

      - name: 🚀 Build APK
        run: |
          npx eas build --platform android --profile production --non-interactive --local --output=app-release.apk

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app-release.apk
